// <auto-generated />
using System;
using MagicVillaApi.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230726034440_AgregandoPrimerasFilas")]
    partial class AgregandoPrimerasFilas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVillaApi.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "",
                            Detalle = "Detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 7, 25, 21, 44, 40, 629, DateTimeKind.Local).AddTicks(8607),
                            FechaCreacion = new DateTime(2023, 7, 25, 21, 44, 40, 629, DateTimeKind.Local).AddTicks(8585),
                            ImageUrl = "",
                            MetrosCuadrados = 20,
                            Nombre = "Villa real",
                            Ocupantes = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "",
                            Detalle = "Segundo detalle de la villa",
                            FechaActualizacion = new DateTime(2023, 7, 25, 21, 44, 40, 629, DateTimeKind.Local).AddTicks(8613),
                            FechaCreacion = new DateTime(2023, 7, 25, 21, 44, 40, 629, DateTimeKind.Local).AddTicks(8611),
                            ImageUrl = "",
                            MetrosCuadrados = 100,
                            Nombre = "Premiun Vista a la Piscina",
                            Ocupantes = 2,
                            Tarifa = 20000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
